# Generated by Django 5.1.1 on 2024-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='longitude',
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='l', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='url',
            field=models.CharField(default='k', max_length=200),
            preserve_default=False,
        ),
    ]
