# Generated by Django 5.1.1 on 2024-10-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_map_latitude_remove_map_longitude_map_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.CharField(max_length=20),
        ),
    ]
