# Generated by Django 5.1.1 on 2024-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_map_name_alter_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.TextField(),
        ),
    ]
