# Generated by Django 4.2.12 on 2024-10-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='cost',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
