# Generated by Django 5.1.1 on 2024-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_cost_destination_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
