# Generated by Django 5.1.1 on 2024-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_cost_destination_location'),
        ('users', '0005_rename_profile_picture_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(related_name='wished_by', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visited_places',
            field=models.ManyToManyField(related_name='visited_by', to='destinations.destination'),
        ),
    ]
