# Generated by Django 5.1.1 on 2024-10-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='location', max_length=100),
            preserve_default=False,
        ),
    ]
