# Generated by Django 5.1.1 on 2024-10-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
    ]
