# Generated by Django 5.1.1 on 2024-10-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_profile',
        ),
    ]
